# Generated by Django 4.2 on 2023-05-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand'),
        ('shopping', '0004_alter_cart_cost_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='order', to='products.product'),
        ),
    ]
