# Generated by Django 4.2 on 2023-04-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
